version: '3.8'

services:
  # Frontend development server
  client:
    build:
      context: ./client
      target: development
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - content-service
      - user-service

  # Content Service
  content-service:
    build:
      context: .
      dockerfile: server/services/content/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/sharedvoices
      - JWT_SECRET=your-secret-key
    depends_on:
      - db
    volumes:
      - ./server/services/content:/app/server/services/content
      - ./server/shared:/app/server/shared
      - ./db:/app/db
      - /app/server/services/content/node_modules
      - /app/server/shared/node_modules

  # User Service
  user-service:
    build:
      context: .
      dockerfile: server/services/user/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/sharedvoices
      - JWT_SECRET=your-secret-key
    depends_on:
      - db
    volumes:
      - ./server/services/user:/app/server/services/user
      - /app/server/services/user/node_modules

  # Interaction Service
  interaction-service:
    build:
      context: .
      dockerfile: server/services/interaction/Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/sharedvoices
      - JWT_SECRET=your-secret-key
    depends_on:
      - db
    volumes:
      - ./server/services/interaction:/app/server/services/interaction
      - /app/server/services/interaction/node_modules

  # Notification Service
  notification-service:
    build:
      context: .
      dockerfile: server/services/notification/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/sharedvoices
      - JWT_SECRET=your-secret-key
    depends_on:
      - db
    volumes:
      - ./server/services/notification:/app/server/services/notification
      - /app/server/services/notification/node_modules

  # Databases
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sharedvoices
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data: