version: '3.8'

services:
  server:
    build:
      context: ./server
      target: builder
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/sharedvoices
    depends_on:
      - mongodb
    command: npm run dev

  client:
    build:
      context: ./client
      target: builder
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    command: npm run dev

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=sharedvoices
    command: mongod --bind_ip_all
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local 